- name: Deploy Royal Hotel Website
  hosts: webservers
  become: yes

  tasks:

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes


    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes


    - name: Copy Royal Hotel webpage
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
