---
- name: Configure Web Servers
  hosts: webservers
  become: yes

  tasks:

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

- name: Copy WAR file
  copy:
    src: files/addressbook-2.1.war
    dest: /var/lib/tomcat9/webapps/AddressBook.war
